/// TTY line discipline with serial input ring buffer.
///
/// The serial interrupt handler pushes received bytes into SERIAL_BUF.
/// read_byte() and poll() check SERIAL_BUF instead of the hardware register.
/// In canonical (cooked) mode: buffers input until newline, handles
/// backspace, Ctrl-C (SIGINT), Ctrl-D (EOF), Ctrl-U (kill line).
/// In raw mode: passes bytes through immediately.

use rux_arch::ConsoleOps;

#[allow(dead_code)] // Used by LineBuffer in line_discipline.rs
const LINE_BUF_SIZE: usize = 4096;

/// Serial input ring buffer — filled by the UART receive interrupt handler.
/// Checked by poll() for POLLIN and drained by read_byte().
///
/// Uses atomic head/tail indices for safe single-producer (IRQ) single-consumer
/// (read_byte) access without disabling interrupts.
const SERIAL_BUF_SIZE: usize = 16384; // 16KB — enough for piped test scripts
static mut SERIAL_BUF: [u8; SERIAL_BUF_SIZE] = [0; SERIAL_BUF_SIZE];
static SERIAL_HEAD: core::sync::atomic::AtomicUsize = core::sync::atomic::AtomicUsize::new(0);
static SERIAL_TAIL: core::sync::atomic::AtomicUsize = core::sync::atomic::AtomicUsize::new(0);

/// State machine for filtering terminal CSI response sequences (e.g. cursor
/// position reports `\033[24;80R`, device attributes `\033[?1;0c`).
/// These responses are generated by the host terminal in reply to ncurses
/// queries and must not reach the application, matching Linux N_TTY behavior.
static mut CSI_FILTER_STATE: u8 = 0; // 0=normal, 1=got ESC, 2=in CSI params

/// Push a byte into the serial ring buffer (called from IRQ handler).
/// Filters out CSI terminal response sequences to prevent poll busy-loops.
#[inline]
pub fn serial_push(b: u8) {
    unsafe {
        match CSI_FILTER_STATE {
            0 => {
                if b == 0x1B { // ESC
                    CSI_FILTER_STATE = 1;
                    return; // don't push ESC yet, might be start of CSI
                }
            }
            1 => {
                if b == b'[' {
                    CSI_FILTER_STATE = 2; // ESC [ = CSI sequence, consume it
                    return;
                }
                // Not CSI — push the deferred ESC and this byte
                CSI_FILTER_STATE = 0;
                serial_push_raw(0x1B);
                serial_push_raw(b);
                return;
            }
            2 => {
                // Inside CSI: params are digits, semicolons, question marks
                // Final byte is 0x40-0x7E (letter or @[\]^_`{|}~)
                if (b >= 0x30 && b <= 0x3F) || b == b';' {
                    return; // intermediate/parameter byte, keep consuming
                }
                if b >= 0x40 && b <= 0x7E {
                    // Final byte — end of CSI sequence, discard entire sequence
                    CSI_FILTER_STATE = 0;
                    return;
                }
                // Unexpected byte — abort filter, push what we have
                CSI_FILTER_STATE = 0;
                serial_push_raw(b);
                return;
            }
            _ => { CSI_FILTER_STATE = 0; }
        }
        serial_push_raw(b);
    }
}

/// Push a byte into the serial ring buffer unconditionally.
#[inline]
fn serial_push_raw(b: u8) {
    use core::sync::atomic::Ordering;
    let head = SERIAL_HEAD.load(Ordering::Relaxed);
    let next = (head + 1) % SERIAL_BUF_SIZE;
    if next == SERIAL_TAIL.load(Ordering::Acquire) { return; } // full, drop byte
    unsafe { SERIAL_BUF[head] = b; }
    SERIAL_HEAD.store(next, Ordering::Release);
}

/// Pop a byte from the serial ring buffer (called from read_byte).
#[inline]
pub fn serial_pop() -> Option<u8> {
    use core::sync::atomic::Ordering;
    let tail = SERIAL_TAIL.load(Ordering::Relaxed);
    if tail == SERIAL_HEAD.load(Ordering::Acquire) { return None; } // empty
    let b = unsafe { SERIAL_BUF[tail] };
    SERIAL_TAIL.store((tail + 1) % SERIAL_BUF_SIZE, Ordering::Release);
    Some(b)
}

/// Check if the serial ring buffer has data.
#[inline]
pub fn serial_has_data() -> bool {
    use core::sync::atomic::Ordering;
    SERIAL_TAIL.load(Ordering::Relaxed) != SERIAL_HEAD.load(Ordering::Relaxed)
}


/// Flush all data from the serial ring buffer.
pub fn serial_flush() {
    use core::sync::atomic::Ordering;
    SERIAL_TAIL.store(SERIAL_HEAD.load(Ordering::Relaxed), Ordering::Release);
}

/// Minimal `core::fmt::Write` adapter for serial console output.
/// Used by strace and kernel debug logging.
pub struct SerialWriter;

impl core::fmt::Write for SerialWriter {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        use rux_arch::ConsoleOps;
        // Kernel output: raw CRLF, bypass termios
        for &b in s.as_bytes() {
            if b == b'\n' { crate::arch::Arch::write_byte(b'\r'); }
            crate::arch::Arch::write_byte(b);
        }
        Ok(())
    }
}

// ── Linux termios constants (full API surface) ───────────────────────

// c_iflag bits
#[allow(dead_code)]
#[allow(dead_code)]
pub const IGNBRK: u32  = 0o000001;
#[allow(dead_code)]
pub const BRKINT: u32  = 0o000002;
#[allow(dead_code)]
pub const IGNPAR: u32  = 0o000004;
#[allow(dead_code)]
pub const PARMRK: u32  = 0o000010;
#[allow(dead_code)]
pub const INPCK: u32   = 0o000020;
pub const ISTRIP: u32  = 0o000040;
pub const INLCR: u32   = 0o000100;
pub const IGNCR: u32   = 0o000200;
pub const ICRNL: u32   = 0o000400;
pub const IXON: u32    = 0o002000;
#[allow(dead_code)]
pub const IXOFF: u32   = 0o010000;

// c_oflag bits
pub const OPOST: u32   = 0o000001;
pub const ONLCR: u32   = 0o000004;
pub const OCRNL: u32   = 0o000010;
pub const ONOCR: u32   = 0o000020;
pub const ONLRET: u32  = 0o000040;

// c_lflag bits
pub const ISIG: u32    = 0o000001;
pub const ICANON: u32  = 0o000002;
pub const ECHO: u32    = 0o000010;
pub const ECHOE: u32   = 0o000020;
pub const ECHOK: u32   = 0o000040;
pub const ECHONL: u32  = 0o000100;
#[allow(dead_code)]
pub const NOFLSH: u32  = 0o000200;
pub const ECHOCTL: u32 = 0o001000;
pub const ECHOKE: u32  = 0o004000;
pub const IEXTEN: u32  = 0o100000;

// c_cc indices
pub const VINTR: usize    = 0;
pub const VQUIT: usize    = 1;
pub const VERASE: usize   = 2;
pub const VKILL: usize    = 3;
pub const VEOF: usize     = 4;
pub const VTIME: usize    = 5;
pub const VMIN: usize     = 6;
pub const VSWTC: usize    = 7;
pub const VSTART: usize   = 8;
pub const VSTOP: usize    = 9;
pub const VSUSP: usize    = 10;
pub const VEOL: usize     = 11;
pub const VREPRINT: usize = 12;
pub const VDISCARD: usize = 13;
pub const VWERASE: usize  = 14;
pub const VLNEXT: usize   = 15;
pub const VEOL2: usize    = 16;
pub const NCCS: usize     = 32;

// ── Termios struct matching Linux musl x86_64 layout (60 bytes) ───────

#[derive(Clone, Copy)]
#[repr(C)]
pub struct Termios {
    pub c_iflag: u32,
    pub c_oflag: u32,
    pub c_cflag: u32,
    pub c_lflag: u32,
    pub c_line: u8,
    pub c_cc: [u8; NCCS],
    pub c_ispeed: u32,
    pub c_ospeed: u32,
}

impl Termios {
    /// Default cooked terminal settings matching Linux defaults.
    pub const fn default_cooked() -> Self {
        let mut cc = [0u8; NCCS];
        cc[VINTR]    = 0x03; // Ctrl-C
        cc[VQUIT]    = 0x1C; // Ctrl-backslash
        cc[VERASE]   = 0x7F; // DEL
        cc[VKILL]    = 0x15; // Ctrl-U
        cc[VEOF]     = 0x04; // Ctrl-D
        cc[VTIME]    = 0;
        cc[VMIN]     = 1;
        cc[VSWTC]    = 0;
        cc[VSTART]   = 0x11; // Ctrl-Q
        cc[VSTOP]    = 0x13; // Ctrl-S
        cc[VSUSP]    = 0x1A; // Ctrl-Z
        cc[VEOL]     = 0;
        cc[VREPRINT] = 0x12; // Ctrl-R
        cc[VDISCARD] = 0x0F; // Ctrl-O
        cc[VWERASE]  = 0x17; // Ctrl-W
        cc[VLNEXT]   = 0x16; // Ctrl-V
        cc[VEOL2]    = 0;
        Self {
            c_iflag: ICRNL | IXON,           // 0x500
            c_oflag: OPOST | ONLCR,          // 0x5
            c_cflag: 0xBF,                   // B38400 | CS8 | CREAD | HUPCL
            c_lflag: ISIG | ICANON | ECHO | ECHOE | ECHOK | ECHOCTL | ECHOKE | IEXTEN, // 0x8A3B
            c_line: 0,
            c_cc: cc,
            c_ispeed: 0,
            c_ospeed: 0,
        }
    }

    #[inline] pub fn is_canonical(&self) -> bool { self.c_lflag & ICANON != 0 }
    #[inline] pub fn echo_enabled(&self) -> bool { self.c_lflag & ECHO != 0 }
    #[inline] pub fn isig_enabled(&self) -> bool { self.c_lflag & ISIG != 0 }
    #[allow(dead_code)]
    #[inline] pub fn echoe_enabled(&self) -> bool { self.c_lflag & ECHOE != 0 }
    #[inline] pub fn echoctl_enabled(&self) -> bool { self.c_lflag & ECHOCTL != 0 }
    #[inline] pub fn iexten_enabled(&self) -> bool { self.c_lflag & IEXTEN != 0 }
    #[inline] pub fn cc(&self, idx: usize) -> u8 { self.c_cc[idx] }
    #[inline] pub fn vmin(&self) -> u8 { self.c_cc[VMIN] }
    #[inline] pub fn vtime(&self) -> u8 { self.c_cc[VTIME] }

    /// Copy raw bytes from user pointer into this struct.
    /// # Safety: ptr must be valid and readable for 60 bytes.
    pub unsafe fn from_user(&mut self, ptr: usize) {
        let src = ptr as *const Termios;
        *self = *src;
    }

    /// Copy this struct to user pointer.
    /// # Safety: ptr must be valid and writable for 60 bytes.
    pub unsafe fn to_user(&self, ptr: usize) {
        let dst = ptr as *mut Termios;
        *dst = *self;
    }

    /// Process an input byte through c_iflag flags.
    /// Returns None if byte should be discarded (IGNCR).
    pub fn input_process(&self, b: u8) -> Option<u8> {
        let mut b = b;
        if self.c_iflag & ISTRIP != 0 { b &= 0x7F; }
        if b == b'\r' {
            if self.c_iflag & IGNCR != 0 { return None; }
            if self.c_iflag & ICRNL != 0 { b = b'\n'; }
        } else if b == b'\n' {
            if self.c_iflag & INLCR != 0 { b = b'\r'; }
        }
        Some(b)
    }

    /// Process an output byte through c_oflag flags.
    /// Returns (byte1, optional_byte2). If ONLCR, \n becomes \r\n.
    pub fn output_process(&self, b: u8, col: &mut usize) -> (u8, Option<u8>) {
        if self.c_oflag & OPOST == 0 {
            // Raw output — no processing
            if b == b'\n' { *col = 0; }
            else if b == b'\r' { *col = 0; }
            else if b >= 0x20 { *col += 1; }
            return (b, None);
        }
        match b {
            b'\n' => {
                if self.c_oflag & ONLRET != 0 { *col = 0; }
                if self.c_oflag & ONLCR != 0 {
                    *col = 0;
                    return (b'\r', Some(b'\n'));
                }
                (b'\n', None)
            }
            b'\r' => {
                if self.c_oflag & ONOCR != 0 && *col == 0 {
                    // Suppress CR at column 0
                    return (b'\r', None); // We'll handle suppression at caller
                }
                if self.c_oflag & OCRNL != 0 {
                    *col = 0;
                    return (b'\n', None);
                }
                *col = 0;
                (b'\r', None)
            }
            _ => {
                if b >= 0x20 && b < 0x7F { *col += 1; }
                else if b == 0x08 && *col > 0 { *col -= 1; } // backspace
                (b, None)
            }
        }
    }
}

/// Global TTY state (single terminal).
pub static mut TTY: Tty = Tty::new();

pub struct Tty {
    /// Shared canonical-mode line buffer (editing, signals, EOF).
    pub line: crate::line_discipline::LineBuffer,
    /// Linux termios settings.
    pub termios: Termios,
    /// Foreground process group for SIGINT delivery.
    pub foreground_pgid: u32,
    /// Session ID that owns this controlling terminal (0 = no session).
    pub session_id: u32,
    /// Window size [rows, cols, xpixel, ypixel].
    pub winsize: [u16; 4],
    /// Current output column (for ONOCR/ONLRET tracking).
    pub col: usize,
}

impl Tty {
    pub const fn new() -> Self {
        Self {
            line: crate::line_discipline::LineBuffer::new(),
            termios: Termios::default_cooked(),
            foreground_pgid: 1,
            session_id: 1, // PID 1's session owns the console
            winsize: [24, 80, 0, 0],
            col: 0,
        }
    }

    /// Check if the TTY has input available (non-blocking).
    pub fn has_input(&self) -> bool {
        if self.line.len > 0 { return true; }
        if serial_has_data() { return true; }
        #[cfg(target_arch = "aarch64")]
        if unsafe { crate::arch::aarch64::console::hw_has_data() } { return true; }
        false
    }

    /// Perform echo for a line discipline echo action.
    fn do_echo<A: ConsoleOps>(&self, echo: crate::line_discipline::Echo) {
        use crate::line_discipline::Echo;
        match echo {
            Echo::None => {}
            Echo::Byte(b) => A::write_byte(b),
            Echo::Ctrl(b) => { A::write_byte(b'^'); A::write_byte(b + 0x40); }
            Echo::Erase => { A::write_byte(0x08); A::write_byte(b' '); A::write_byte(0x08); }
            Echo::EraseN(n) => {
                for _ in 0..n { A::write_byte(0x08); A::write_byte(b' '); A::write_byte(0x08); }
            }
            Echo::Str(s) => A::write_bytes(s),
            Echo::Reprint => {
                A::write_bytes(b"^R\n");
                A::write_bytes(self.line.content());
            }
        }
    }

    /// Read from terminal in canonical mode.
    /// Uses the shared LineBuffer for editing, signals, and EOF.
    pub unsafe fn read_canonical<A: ConsoleOps>(
        &mut self, buf: *mut u8, len: usize,
    ) -> isize {
        use crate::line_discipline::LineEvent;
        loop {
            let raw = A::read_byte();
            let (event, echo) = self.line.process(raw, &self.termios);
            self.do_echo::<A>(echo);

            match event {
                LineEvent::Signal(signum) => {
                    crate::syscall::posix::kill(-(self.foreground_pgid as isize), signum as usize);
                    return crate::errno::EINTR;
                }
                LineEvent::Eof => return 0,
                LineEvent::EofFlush | LineEvent::Complete => break,
                LineEvent::Continue => continue,
            }
        }

        // Copy from line buffer to user buffer
        let n = len.min(self.line.len);
        core::ptr::copy_nonoverlapping(self.line.buf.as_ptr(), buf, n);

        // Shift remaining data
        if n < self.line.len {
            let remaining = self.line.len - n;
            core::ptr::copy(self.line.buf.as_ptr().add(n), self.line.buf.as_mut_ptr(), remaining);
            self.line.len = remaining;
        } else {
            self.line.len = 0;
        }

        n as isize
    }

    /// Read from terminal in raw mode — respects VMIN/VTIME.
    ///
    /// VMIN=1, VTIME=0 (default): block until 1 byte, return it immediately.
    /// VMIN=0, VTIME=0: non-blocking, return what's available (0 if nothing).
    /// VMIN>0, VTIME=0: block until VMIN bytes.
    /// VMIN=0, VTIME>0: wait up to VTIME*100ms, return what arrives.
    /// VMIN>0, VTIME>0: inter-byte timeout after first byte.
    pub unsafe fn read_raw<A: ConsoleOps>(
        &mut self, buf: *mut u8, len: usize,
    ) -> isize {
        if len == 0 { return 0; }
        let t = &self.termios;
        let vmin = (t.vmin() as usize).min(len);
        let vtime = t.vtime();
        let ptr = buf;

        // Case 1: VMIN=0, VTIME=0 → pure non-blocking, return all available
        if vmin == 0 && vtime == 0 {
            let mut got = 0usize;
            while got < len {
                if let Some(raw) = serial_pop() {
                    if let Some(b) = t.input_process(raw) {
                        *ptr.add(got) = b;
                        got += 1;
                    }
                } else {
                    #[cfg(target_arch = "aarch64")]
                    if A::has_byte() {
                        let raw = A::read_byte();
                        if let Some(b) = t.input_process(raw) {
                            *ptr.add(got) = b;
                            got += 1;
                        }
                        continue;
                    }
                    break;
                }
            }
            return got as isize;
        }

        // Case 2: VMIN=0, VTIME>0 → deadline, return whatever collected
        if vmin == 0 && vtime > 0 {
            let deadline = {
                use rux_arch::TimerOps;
                crate::arch::Arch::ticks() + (vtime as u64) * 100
            };
            let mut got = 0usize;
            loop {
                if let Some(raw) = serial_pop() {
                    if let Some(b) = t.input_process(raw) {
                        *ptr.add(got) = b;
                        got += 1;
                        if got >= len { break; }
                    }
                } else {
                    use rux_arch::TimerOps;
                    if crate::arch::Arch::ticks() >= deadline { break; }
                    // Sleep briefly
                    let task_idx = crate::task_table::current_task_idx();
                    crate::task_table::TASK_TABLE[task_idx].state =
                        crate::task_table::TaskState::WaitingForPoll;
                    crate::task_table::TASK_TABLE[task_idx].wake_at = deadline;
                    crate::task_table::poll_wait_register(task_idx);
                    let sched = crate::scheduler::get();
                    sched.tasks[task_idx].entity.state = rux_sched::TaskState::Interruptible;
                    sched.dequeue_current();
                    sched.need_resched |= 1u64 << crate::percpu::cpu_id() as u32;
                    sched.schedule();
                }
            }
            return got as isize;
        }

        // Case 3: VMIN>0, VTIME=0 → block until VMIN bytes
        // Case 4: VMIN>0, VTIME>0 → block for first byte, then inter-byte timeout
        let target = vmin.min(len);
        let mut got = 0usize;
        while got < target {
            let raw = A::read_byte();
            if let Some(b) = t.input_process(raw) {
                *ptr.add(got) = b;
                got += 1;
                // Case 4: after first byte, apply inter-byte timeout
                if got > 0 && got < target && vtime > 0 {
                    let deadline = {
                        use rux_arch::TimerOps;
                        crate::arch::Arch::ticks() + (vtime as u64) * 100
                    };
                    // Collect remaining bytes with timeout
                    while got < target {
                        if let Some(raw2) = serial_pop() {
                            if let Some(b2) = t.input_process(raw2) {
                                *ptr.add(got) = b2;
                                got += 1;
                            }
                        } else {
                            use rux_arch::TimerOps;
                            if crate::arch::Arch::ticks() >= deadline { break; }
                            let task_idx = crate::task_table::current_task_idx();
                            crate::task_table::TASK_TABLE[task_idx].state =
                                crate::task_table::TaskState::WaitingForPoll;
                            crate::task_table::TASK_TABLE[task_idx].wake_at = deadline;
                            crate::task_table::poll_wait_register(task_idx);
                            let sched = crate::scheduler::get();
                            sched.tasks[task_idx].entity.state = rux_sched::TaskState::Interruptible;
                            sched.dequeue_current();
                            sched.need_resched |= 1u64 << crate::percpu::cpu_id() as u32;
                            sched.schedule();
                        }
                    }
                    break;
                }
            }
        }
        got as isize
    }

    /// Write bytes to the console with output processing (c_oflag).
    /// Called for userspace writes to stdout/stderr on the console.
    pub fn write_processed<A: ConsoleOps>(&mut self, data: &[u8]) {
        for &b in data {
            let (b1, b2) = self.termios.output_process(b, &mut self.col);
            A::write_byte(b1);
            if let Some(b2) = b2 {
                A::write_byte(b2);
            }
        }
    }

    /// Flush the line buffer (for TCSETSF).
    pub fn flush_input(&mut self) {
        self.line.reset();
    }
}
